### ISSUE TITLE
Schaltplan

### ISSUE THREAD

**Issue by htyx75** [mischk/audioadventcalendar_ng#2]
Moin aus Hamburg,
ich finde Deine Idee super und würde das für meine Kids gerne nachbauen.
Gibt es die Möglichkeit, dass Du mir den genauen Schaltplan zusendest?

Gruss

Henrik

**Comment by Landixus** [comment]
Schaltplan findet man hier: 
https://www.heise.de/make/artikel/Statt-Schokolade-Audio-Adventskalender-zum-Selberbauen-4157308.html

**Comment by RcTomcat1** [comment]
Der ist nur leider falsch......
da fehlt ein 1kohm Wiederstand zwischen RX und D3. Ohne den ist der JQ6500 direkt nach dem einschalten Elektroschrott......Musste ich leider soeben auf die harte Tour lernen

**Comment by lotte67890** [comment]
Bist du sicher dass es ein 1kohm WIderstand ist? Wenn ich den Farbcode halbwegs erkennen kann würde ich sagen 3.7kohm oder 4kohm...

**Comment by RcTomcat1** [comment]
Steht zumindest so in der JQ6500 Serial Doku 
https://github.com/sleemanj/JQ6500_Serial
To use this library with a 5v Arduino, connect as follows.
JQ6500 Module | Arduino
-- | --
RX | through a 1K Resistor then to pin 9
TX | pin 8
GND (any of) | GND
VCC (any of) | VCC

Ich sehe in dem einen Bild Gelb, Violet, Rot, Gold. Das wäre ein 4,7K Ohm oder?

**Comment by lotte67890** [comment]
Yepp, das wären 4.7k, ich bin mir nur unschlüssig ob der "erste" Ring gelb oder Orange ist.. Allerdings wären 3.7k relativ unüblich... Andererseits, je höher desto weniger geht beim Versuch kaputt... Kann höchstens sein dass es nicht funktioniert...

**Comment by RcTomcat1** [comment]
Also ohne Wiederstand funktioniert es nur ganze 5 Sekunden XD. Hoffe mal Ich hab mein JQ6500 nicht geröstet.....
Habe mal 3,7 und 4,7K ohm bestellt und werde testen. Ersatz für den JQ ist auch bestellt, dauert halt wieder 3 Wochen. Könnte gerade so klappen mit Dezember

**Comment by htyx75** [comment]
Laut Author wird kein Widerstand benötigt.
Da im Manual einer genannt wird, sollte da unbedingt ein 1k Widerstand hin.

sent from my iPhone

**Comment by Landixus** [comment]
Ich hab keine Probleme ohne Widerstand, benutze den 28p.
Aber ich denke 1k sollten langen.
Hab zum Glück Reichelt um die Ecke, das ist gut wenn man schnell was braucht, ausser am Feiertag :)

**Comment by RcTomcat1** [comment]
> 
> 
> Ich hab keine Probleme ohne Widerstand, benutze den 28p.
> Aber ich denke 1k sollten langen.
> Hab zum Glück Reichelt um die Ecke, das ist gut wenn man schnell was braucht, ausser am Feiertag :)

Hm ok, mein 28p hat eben nur 5 Sekunden was getan und dann war tot.
Kein Busy Signal mehr und damit keine LEDs, kein Sound.

**Comment by htyx75** [comment]
Ich hab den JQ6500 bei AliExpress bestellt. Hat keine zwei Wochen gedauert.


sent from my iPhone

**Comment by lotte67890** [comment]
Noch ne Frage, laut Schaltplan wird ein 0,01uf Kondensator an den 5v Ausgang angeschlossen, ich finde aber keinen... 0,1uf wäre verfügbar... sollte der auch funktionieren?

**Comment by Landixus** [comment]
Der ist nur zum glätten, ich würde den bei einer Batterie weg lassen.

**Comment by mischk** [comment]
Ich habe das ohne Widersand verschaltet, und er läuft ohne Probleme. Aber es schadet auf keinen Fall einen einzubauen.
