### ISSUE TITLE
I have an issue with the folder structure

### ISSUE THREAD

**Issue by Landixus** [mischk/audioadventcalendar_ng#3]
I cannot not figured out the folder structure.
What i need to do exact on the sd card?

With the example i can play mp3 from the JQ6500
But with your code i have no play. It says Playing in serial Monitor:
Audio Advent Calendar by Mischka

playing track Number: 20

I have tried a folder "000" wit a mp3file  "020.mp3" in the folder, but it will not play the sound!?
Have you an idea?

**Comment by Landixus** [comment]
Ok solved it.
The instructions in Heise.de is not correct for the Folder.
You need to have following Structure:
"Folder" 00
"MP3_Item" 020

**Comment by mischk** [comment]
thank you!
